add_newline = true
command_timeout = 200
format = "[$directory$git_branch$git_status]($style)$character"

[character]
error_symbol = "[❯](bold red)"
success_symbol = "[❯](bold purple)"
vimcmd_symbol = "[❮](bold purple)"

[directory]
truncation_length = 2
truncation_symbol = "…/"
repo_root_style = "bold cyan"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "

[git_branch]
format = "[$branch]($style) "
style = "italic bright-black"

[git_status]
format     = '$ahead_behind$conflicted$untracked$modified$staged$renamed$deleted$stashed'
ahead      = "[⇡${count}](blue) "
diverged   = "[⇕⇡${ahead_count}⇣${behind_count}](red) "
behind     = "[⇣${count}](yellow) "
conflicted = "[](bold red) "
up_to_date = "[](green) "
untracked  = "[?](bright-black) "
modified   = "[](yellow) "
stashed    = ""
staged     = ""
renamed    = ""
deleted    = ""
