#!/usr/bin/env zsh

_load_plugin() {
  local name="$1"; shift
  for path in "$@"; do
    if [[ -f "$path" ]]; then
      source "$path"
      return
    fi
  done
}

_load_plugin zsh-autosuggestions \
  "${HOMEBREW_PREFIX}/share/zsh-autosuggestions/zsh-autosuggestions.zsh" \
  "/usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh" \
  "${HOME}/.local/share/zsh-autosuggestions/zsh-autosuggestions.zsh"

# Must be sourced last
_load_plugin zsh-syntax-highlighting \
  "${HOMEBREW_PREFIX}/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" \
  "/usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" \
  "${HOME}/.local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"

unfunction _load_plugin
